#!/bin/bash

passage1="<s> YOU ARE STANDING ON A SANDY WHITE BEACH OF THE GULF OF MEXICO LOOKING OUT OVER THE WATER YOU NOTICE A HUGE BIRD WITH LONG NARROW WINGS GLIDING OVER THE OCEAN SUDDENLY THE BIRD TUCKS ITS WINGS IN ITS SIDES AND DROPS A HUNDRED FEET STRAIGHT DOWN TO THE WATER BEFORE YOU CAN BLINK IT SHOOTS OUT OF THE SEA WITH A LARGE FISH IN ITS CLAWS AND SOARS UPWARD TO THE SKY YOU HAVE JUST SEEN AN OSPREY CATCH ITS BREAKFAST UNFORTUNATELY THE SIGHT YOU HAVE JUST SEEN HAS BEEN QUITE RARE THEY ARE FAR FEWER OSPREYS TODAY THAN THERE ONCE WERE THE REASON FOR THIS IS THAT PEOPLE HAVE MOVED INTO PLACES THAT WERE OSPREY NESTS AREAS AS MORE AND MORE PEOPLE SETTLE IN THESE AREAS THEY CUT DOWN TREES TO BUILD HOUSES SHOPS AND BUILDING THE GRADUAL INFLUENCE OF CIVILIZATION HAS LEFT OSPREYS WITH FEWER PLACES TO BUILD THEIR NESTS IN ADDITION PEOPLE BEGAN TO USE FERTILIZERS AND EVERY CHEMICALS WOULD DRAIN INTO THE WATER SUPPLY THIS POISONED THE FISH WHICH OSPREYS FEED ON PEOPLE SOMETIMES FRIGHTENED OSPREYS AWAY FROM THEIR NEST LEAVING THEIR EGGS TO BE DESTROYED BY THE HOT SUN </s>"
passage2="<s> I LIVE WITH MY COUSIN JACKSON WHO IS A MARINE BIOLOGIST HIS JOB IS TO STUDY THE CONVERSATIONS THAT WHALES HAVE WITH EACH OTHER JACKSON SAYS THE SOUNDS THESE WONDROUS CREATURES MAKE ARE REALLY LIKE SINGING IF YOU VISIT OUR HOUSE YOU WILL HEAR THESE SONGS PLAYING ON OUR STEREO MORE THAN ANY OTHER KIND OF MUSIC THESE HAUNTING SOUNDS HAVE BEEN DESCRIBED AS CREAKS GROANS MOANS CHIRPS WHISTLES AND SQUEAKS THE SONGS ARE NOT JUST SOUNDS BUT REALLY MELODIES THAT WITH A BEGINNING MIDDLE AND END A WHALE WILL REPEAT THE SAME SONG OVER AND OVER BUT SLOWLY THE SONG CHANGES OVER TIME AND EVERY FEW YEARS NEW SONGS APPEAR HUMPBACK WHALES ARE FOUND THROUGHOUT THE WORLD MALES FROM THE SAME AREA SING SIMILAR MELODIES JUST LIKE YOU CAN SOMETIMES TELL WHERE PEOPLE COME FROM JUST BY LISTENING TO THEM AND TALK JACKSON CAN TELL WHERE THE WHALE COMES FROM BY LISTENING TO RECORDINGS OF ITS SONG MY COUSIN THINKS THE SONGS ARE A WAY OF SHARING INFORMATION AND CREATING AND MAINTAINING A SOCIAL COMMUNITY HIS RESEARCH EXAMINES HOW BABY WHALES LEARNED THE SONGS OF THEIR REGION MALE HUMPBACK WHALES CAN PRODUCE SONGS THAT LAST FOR UP TO TWENTY MINUTES </s>"
passage3="<s> MOUNT EVEREST A MOUNTAIN PEAK LOCATED IN ASIA IS THE HIGHEST MOUNTAIN IN THE WORLD IT IS NAMED AFTER GEORGE EVEREST THE SCIENTIST WHO FIRST MAPPED THE AREA CLIMBERS HAVE MADE MANY ATTEMPTS TO REACH THE MOUNTAIN'S PEAK ONE OF THE FIRST OF THESE EXPEDITIONS OCCURRED ABOUT EIGHTY YEARS AGO HOWEVER IT WAS NOT UNTIL THIRTY YEARS LATER THAT TWO MEN FINALLY CONQUERED MOUNT EVEREST BY THE END OF THE CENTURY MORE THAN SIX HUNDREDS CLIMBERS HAD CLIMBED TO THE TOP THE CLIMB IS VERY DANGEROUS THOUGH MORE THAN ONE HUNDRED PEOPLE HAVE DIED WHILE ATTEMPTING THE CLIMB CLIMBING TO THE TOP OF MOUNT EVEREST IS A DREAM OF MANY EXPLORERS ONE OF THEM WAS ONCE ASKED WHY THE MOUNTAIN HOLDS SUCH AN ATTRACTION FOR SO MANY PEOPLE HE REPLIED SIMPLY BECAUSE IT IS THERE OTHER CLIMBERS HAVE OTHER REASONS FOR MAKING THE CLIMB BUT MOST WOULD PROBABLY AGREE THAT THE CLIMB REPRESENTS A TREMENDOUS CHALLENGE TO CLIMB TO THE PEAK CLIMBERS MUST BATTLE ICE SNOW AND HOWLING WINDS THEY MUST CROSS HAZARDOUS GAPS IN THE ICE AS BIG AS CANYONS CLIMBERS SOMETIMES LOSE FINGERS AND TOES TO FROSTBITE THE LACK OF OXYGEN IS ONE OF THE BIGGEST PROBLEMS THAT CLIMBERS FACE </s>"

. ${LOCAL_DIR}/g300_list_gen.sh >> list.txt

let subset=1
while read line
do 
	if [ ${subset} -gt ${CORPUS_SUBSET} ]; then
		break;
	else
		let subset=${subset}+1
	fi
	passage=`echo $line | sed "s/^[0-9]\+\.[a-z]\+//g"`
	if [[ ${passage} == 1 ]]; then
		echo "$line $passage1"
	elif [[ $passage == 2 ]]; then
		echo "$line $passage2"
	elif [[ $passage == 3 ]]; then
		echo "$line $passage3"
	else
		echo "g300_mklist: wrong passage number."
		exit 1
	fi
done < list.txt

rm list.txt
